/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: fieldops_Envelope, fieldops_GroupingFilesResponse */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: fieldops_Envelope, fieldops_GroupingFilesResponse
#endif
PB_BIND(fieldops_Envelope, fieldops_Envelope, 4)


PB_BIND(fieldops_SourcesRequest, fieldops_SourcesRequest, AUTO)


PB_BIND(fieldops_SourcesResponse, fieldops_SourcesResponse, AUTO)


PB_BIND(fieldops_Source, fieldops_Source, AUTO)


PB_BIND(fieldops_GroupingFilesRequest, fieldops_GroupingFilesRequest, AUTO)


PB_BIND(fieldops_GroupingFilesResponse, fieldops_GroupingFilesResponse, 4)


PB_BIND(fieldops_GroupingFile, fieldops_GroupingFile, 2)


PB_BIND(fieldops_FileOpenRequest, fieldops_FileOpenRequest, 2)


PB_BIND(fieldops_FileOpenResponse, fieldops_FileOpenResponse, 2)


PB_BIND(fieldops_ErrorResponse, fieldops_ErrorResponse, AUTO)



